:wrench: fix CI

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -177,13 +177,13 @@ jobs:
             target: riscv64gc-unknown-linux-gnu
             python_version: '3.14t'
           - manylinux: musllinux_1_1
-            target: riscv64gc-unknown-linux-musl
+            target: riscv64-unknown-linux-musl
             python_version: '3.10'
           - manylinux: musllinux_1_1
-            target: riscv64gc-unknown-linux-musl
+            target: riscv64-unknown-linux-musl
             python_version: '3.13t'
           - manylinux: musllinux_1_1
-            target: riscv64gc-unknown-linux-musl
+            target: riscv64-unknown-linux-musl
             python_version: '3.14t'
 
     steps:
@@ -244,7 +244,7 @@ jobs:
         if: matrix.target == 'aarch64' && matrix.manylinux == 'manylinux2014'
         uses: PyO3/maturin-action@v1
         env:
-          CFLAGS_aarch64_unknown_linux_gnu: "-D__ARM_ARCH=8"
+          CFLAGS_aarch64_unknown_linux_gnu: "-D__ARM_ARCH=8 -DAT_HWCAP2=26"
           UNSAFE_PYO3_SKIP_VERSION_CHECK: 1
         with:
           target: ${{ matrix.target }}
@@ -375,6 +375,30 @@ jobs:
             sudo apt-get install -y linux-headers-generic || echo "no apt support"
             sudo apt-get install -y gcc-multilib || echo "no apt support"
             export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/usr/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot"
+
+      - name: Build wheels (riscv+manylinux_2_39 workaround)
+        if: matrix.target == 'riscv64-unknown-linux-musl' && matrix.manylinux == 'musllinux_1_1'
+        uses: PyO3/maturin-action@v1
+        env:
+          UNSAFE_PYO3_SKIP_VERSION_CHECK: 1
+        with:
+          target: ${{ matrix.target }}
+          args: --release --out dist --interpreter ${{ matrix.python_version }}
+          sccache: 'true'
+          manylinux: ${{ matrix.manylinux }}
+          docker-options: -e UNSAFE_PYO3_SKIP_VERSION_CHECK=1
+          container: ghcr.io/rust-cross/rust-musl-cross:riscv64gc-musl
+          before-script-linux: |
+            sudo apt-get update || echo "no apt support"
+            sudo apt-get install -y libclang || echo "no apt support"
+            sudo apt-get install -y libc6 || echo "no apt support"
+            sudo apt-get install -y libc6-dev || echo "no apt support"
+            sudo apt-get install -y libclang-dev || echo "no apt support"
+            sudo apt-get install -y clang || echo "no apt support"
+            sudo apt-get install -y linux-headers-generic || echo "no apt support"
+            sudo apt-get install -y gcc-multilib wget || echo "no apt support"
+            sudo wget https://gist.githubusercontent.com/Ousret/ae53d8c725a2ad48c133afce313ffdcc/raw/3671b2081742f3d5152cd67f1d813ea3cbd84d50/queue.h -O /usr/local/musl/riscv64-unknown-linux-musl/include/sys/queue.h || echo "compat fail"
+            export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/usr/local/musl/riscv64-unknown-linux-musl"
 
       - name: Build wheels (armv7l+manylinux workaround)
         if: matrix.target == 'armv7l' && matrix.manylinux == 'manylinux2014'
