:wrench: fix deprecation warnings for upload/download artifacts

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -142,7 +142,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        target: [ x86_64, s390x, aarch64, armv7l, ppc64le, ppc64 ]
+        target: [ x86_64, s390x, aarch64, armv7l, ppc64le, ppc64, x86 ]
         python_version: [ '3.10', 'pypy-3.7', 'pypy-3.8', 'pypy-3.9', 'pypy-3.10', '3.13t' ]
         manylinux: [ 'manylinux2014', 'musllinux_1_1' ]
         exclude:
@@ -152,6 +152,12 @@ jobs:
             target: ppc64
           - manylinux: musllinux_1_1
             target: ppc64le
+          - manylinux: musllinux_1_1
+            target: x86
+          - manylinux: musllinux_1_1
+            target: x86
+          - manylinux: musllinux_1_1
+            target: x86
 
     steps:
       - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
@@ -164,7 +170,7 @@ jobs:
         with:
           python-version: 3.13t
       - name: Build wheels (no workarounds)
-        if: matrix.target == 'x86_64'
+        if: matrix.target == 'x86_64' || matrix.target == 'x86'
         uses: PyO3/maturin-action@v1
         env:
           UNSAFE_PYO3_SKIP_VERSION_CHECK: 1
@@ -183,7 +189,11 @@ jobs:
             sudo apt-get install -y clang || echo "no apt support"
             sudo apt-get install -y linux-headers-generic || echo "no apt support"
             sudo apt-get install -y gcc-multilib wget || echo "no apt support"
-            sudo wget https://git.alpinelinux.org/aports/plain/main/bsd-compat-headers/queue.h -O /usr/local/musl/bin/../x86_64-unknown-linux-musl/include/sys/queue.h || echo "compat fail"
+            sudo wget https://git.alpinelinux.org/aports/plain/main/bsd-compat-headers/queue.h -O /usr/local/musl/bin/../x86_64-unknown-linux-musl/include/sys/queue.h || echo "compat x64 fail"
+            sudo wget https://git.alpinelinux.org/aports/plain/main/bsd-compat-headers/queue.h -O /usr/local/musl/bin/../x86-unknown-linux-musl/include/sys/queue.h || echo "compat x86 fail"
+            sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm
+            sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-2-3.el7.centos.noarch.rpm
+            sudo yum -y install http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/l/llvm-toolset-7-clang-4.0.1-1.el7.x86_64.rpm
             yum install -y llvm-toolset-7-clang || echo "not yum based"
             source /opt/rh/llvm-toolset-7/enable || echo "not yum based"
 
@@ -347,10 +357,10 @@ jobs:
             export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/usr/local/musl/armv7-unknown-linux-musleabihf"
 
       - name: Upload wheels
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
         with:
-          name: wheels
-          path: dist
+          name: wheels-linux-${{ matrix.target }}-${{ matrix.manylinux }}-${{ matrix.python_version }}
+          path: dist/*.whl
 
   windows:
     needs:
@@ -422,10 +432,10 @@ jobs:
           args: --release --out dist
           sccache: 'true'
       - name: Upload wheels
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
         with:
-          name: wheels
-          path: dist
+          name: wheels-windows-${{ matrix.target }}-${{ matrix.python_version }}
+          path: dist/*.whl
 
   macos:
     needs:
@@ -457,10 +467,10 @@ jobs:
           args: --release --out dist --interpreter ${{ matrix.python_version }}
           sccache: 'true'
       - name: Upload wheels
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
         with:
-          name: wheels
-          path: dist
+          name: wheels-macos-${{ matrix.target }}-${{ matrix.python_version }}
+          path: dist/*.whl
 
   sdist:
     needs:
@@ -476,25 +486,25 @@ jobs:
           command: sdist
           args: --out dist
       - name: Upload sdist
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
         with:
-          name: wheels
-          path: dist
+          name: wheels-sdist
+          path: dist/*.tar.gz
 
   checksum:
     name: compute hashes
     runs-on: ubuntu-22.04
     needs: [windows, macos, linux, sdist]
-    if: "startsWith(github.ref, 'refs/tags/')"
     outputs:
       hashes: ${{ steps.compute.outputs.hashes }}
     steps:
       - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
       - name: Download distributions
-        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
+        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
         with:
-          name: wheels
+          pattern: wheels-*
           path: dist
+          merge-multiple: true
       - name: Collected dists
         run: |
           tree dist
@@ -525,11 +535,18 @@ jobs:
     permissions:
       id-token: write
     steps:
-      - uses: actions/download-artifact@v3
+      - name: Download distributions
+        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
         with:
-          name: wheels
+          pattern: wheels-*
+          path: dist
+          merge-multiple: true
+      - name: "Upload dists to GitHub Release"
+        env:
+          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+        run: |
+          gh release upload ${{ github.ref_name }} dist/* --repo ${{ github.repository }}
       - name: Publish to PyPI
-        uses: PyO3/maturin-action@v1
+        uses: "pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70" # v1.12.3
         with:
-          command: upload
-          args: --non-interactive --skip-existing *
+          attestations: true
